format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
license_template_path = "./license-template"
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
